"""File extension to tree-sitter language mapping.

Maps file extensions to language names recognized by
tree-sitter-language-pack's process() API. The full list of
170+ supported languages is available via manifest_languages().

This map covers common file extensions. Languages without
entries here fall back to token-based chunking.
"""

EXT_TO_LANG: dict[str, str] = {
    # Systems / compiled
    ".c": "c",
    ".h": "c",
    ".cpp": "cpp",
    ".cxx": "cpp",
    ".cc": "cpp",
    ".hpp": "cpp",
    ".hxx": "cpp",
    ".cs": "csharp",
    ".d": "d",
    ".go": "go",
    ".java": "java",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".m": "objc",
    ".rs": "rust",
    ".scala": "scala",
    ".swift": "swift",
    ".zig": "zig",
    ".v": "v",
    ".odin": "odin",
    ".hare": "hare",
    ".nim": "nim",
    ".ada": "ada",
    ".adb": "ada",
    ".ads": "ada",
    ".f90": "fortran",
    ".f95": "fortran",
    ".f03": "fortran",
    ".f": "fortran",
    ".pas": "pascal",
    ".cobol": "cobol",
    ".cob": "cobol",
    ".cbl": "cobol",
    # Scripting / dynamic
    ".py": "python",
    ".pyi": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".ts": "typescript",
    ".tsx": "tsx",
    ".rb": "ruby",
    ".php": "php",
    ".lua": "lua",
    ".luau": "luau",
    ".pl": "perl",
    ".pm": "perl",
    ".r": "r",
    ".R": "r",
    ".jl": "julia",
    ".ex": "elixir",
    ".exs": "elixir",
    ".erl": "erlang",
    ".hrl": "erlang",
    ".clj": "clojure",
    ".cljs": "clojure",
    ".cljc": "clojure",
    ".ml": "ocaml",
    ".mli": "ocaml_interface",
    ".hs": "haskell",
    ".fs": "fsharp",
    ".fsi": "fsharp_signature",
    ".fsx": "fsharp",
    ".elm": "elm",
    ".purs": "purescript",
    ".rkt": "racket",
    ".scm": "scheme",
    ".el": "elisp",
    ".lisp": "commonlisp",
    ".cl": "commonlisp",
    ".fnl": "fennel",
    ".janet": "janet",
    ".dart": "dart",
    ".gd": "gdscript",
    ".gleam": "gleam",
    ".groovy": "groovy",
    ".gradle": "groovy",
    ".tcl": "tcl",
    ".fish": "fish",
    ".ps1": "powershell",
    ".psm1": "powershell",
    ".psd1": "powershell",
    ".matlab": "matlab",
    ".pony": "pony",
    ".hack": "hack",
    ".hx": "haxe",
    ".squirrel": "squirrel",
    ".nut": "squirrel",
    ".nix": "nix",
    ".star": "starlark",
    ".bzl": "starlark",
    ".smali": "smali",
    # Shell
    ".sh": "bash",
    ".bash": "bash",
    ".zsh": "bash",
    # Web / markup
    ".html": "html",
    ".htm": "html",
    ".xml": "xml",
    ".xsl": "xml",
    ".xslt": "xml",
    ".css": "css",
    ".scss": "scss",
    ".vue": "vue",
    ".svelte": "svelte",
    ".astro": "astro",
    ".twig": "twig",
    ".md": "markdown",
    ".markdown": "markdown",
    # Functional / blockchain
    ".sol": "solidity",
    ".cairo": "cairo",
    ".fc": "func",
    ".clar": "clarity",
    ".rego": "rego",
    # Data / config
    ".json": "json",
    ".jsonnet": "jsonnet",
    ".libsonnet": "jsonnet",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "toml",
    ".ini": "ini",
    ".cfg": "ini",
    ".properties": "properties",
    ".ron": "ron",
    ".kdl": "kdl",
    ".hcl": "hcl",
    ".tf": "terraform",
    ".tfvars": "terraform",
    ".graphql": "graphql",
    ".gql": "graphql",
    ".proto": "proto",
    ".thrift": "thrift",
    ".capnp": "capnp",
    ".smithy": "smithy",
    ".prisma": "prisma",
    ".beancount": "beancount",
    ".sql": "sql",
    ".sparql": "sparql",
    # Build / CI
    ".cmake": "cmake",
    ".ninja": "ninja",
    ".meson": "meson",
    ".gn": "gn",
    ".pp": "puppet",
    ".tex": "latex",
    ".bib": "bibtex",
    ".typst": "typst",
    ".dockerfile": "dockerfile",
    ".bicep": "bicep",
    # HDL / embedded / GPU
    ".vhdl": "vhdl",
    ".vhd": "vhdl",
    ".sv": "verilog",
    ".svh": "verilog",
    ".verilog": "verilog",
    ".cuda": "cuda",
    ".cu": "cuda",
    ".glsl": "glsl",
    ".hlsl": "hlsl",
    ".wgsl": "wgsl",
    ".ispc": "ispc",
    ".s": "asm",
    ".asm": "asm",
    ".ll": "llvm",
    ".lds": "linkerscript",
    ".wat": "wat",
    ".wast": "wast",
}
